-- Salon-local operating hours and exceptional schedule blocks. Timestamps stay
-- in timestamptz; weekly rules are evaluated in the salon's canonical zone.

create table public.business_hours (
  weekday smallint primary key check (weekday between 0 and 6),
  is_open boolean not null default true,
  opens_at time,
  closes_at time,
  break_starts_at time,
  break_ends_at time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_hours_open_times check (
    (not is_open)
    or (opens_at is not null and closes_at is not null and opens_at < closes_at)
  ),
  constraint business_hours_break_pair check (
    (break_starts_at is null) = (break_ends_at is null)
  ),
  constraint business_hours_break_inside_opening check (
    break_starts_at is null
    or (
      is_open
      and opens_at < break_starts_at
      and break_starts_at < break_ends_at
      and break_ends_at < closes_at
    )
  )
);

-- Start permissively so applying this migration does not invalidate the salon's
-- current operation. The authorized user can configure the real week in UI.
insert into public.business_hours (weekday, is_open, opens_at, closes_at)
select weekday, true, time '00:00', time '23:59:59.999999'
from generate_series(0, 6) as weekday;

create table public.schedule_blocks (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_blocks_valid_range check (starts_at < ends_at)
);

create index schedule_blocks_starts_at_idx on public.schedule_blocks (starts_at);
create index schedule_blocks_range_idx on public.schedule_blocks
using gist (tstzrange(starts_at, ends_at, '[)'));

create trigger business_hours_set_updated_at
before update on public.business_hours
for each row execute function agenda_salao_private.set_updated_at();

create trigger schedule_blocks_set_updated_at
before update on public.schedule_blocks
for each row execute function agenda_salao_private.set_updated_at();

alter table public.business_hours enable row level security;
alter table public.schedule_blocks enable row level security;

create policy salon_account_select on public.business_hours
for select to authenticated
using ((select agenda_salao_private.is_salon_user()));

create policy salon_account_insert on public.business_hours
for insert to authenticated
with check ((select agenda_salao_private.is_salon_user()));

create policy salon_account_update on public.business_hours
for update to authenticated
using ((select agenda_salao_private.is_salon_user()))
with check ((select agenda_salao_private.is_salon_user()));

create policy salon_account_select on public.schedule_blocks
for select to authenticated
using ((select agenda_salao_private.is_salon_user()));

create policy salon_account_insert on public.schedule_blocks
for insert to authenticated
with check ((select agenda_salao_private.is_salon_user()));

create policy salon_account_delete on public.schedule_blocks
for delete to authenticated
using ((select agenda_salao_private.is_salon_user()));

revoke all on table public.business_hours, public.schedule_blocks
from public, anon, authenticated;
grant select, insert, update on table public.business_hours to authenticated;
grant select, insert, delete on table public.schedule_blocks to authenticated;
grant usage, select on sequence public.schedule_blocks_id_seq to authenticated;

create or replace function agenda_salao_private.validate_booking_schedule()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  salon_zone constant text := 'America/Sao_Paulo';
  local_start timestamp;
  local_end timestamp;
  hours public.business_hours%rowtype;
begin
  if new.status not in ('scheduled', 'confirmed') then
    return new;
  end if;

  -- Serialize booking/block checks so two concurrent transactions cannot both
  -- pass their reciprocal checks before either row becomes visible.
  perform pg_advisory_xact_lock(731945210);

  local_start := new.starts_at at time zone salon_zone;
  local_end := new.ends_at at time zone salon_zone;

  if local_start::date <> local_end::date then
    raise exception 'booking must start and end on the same salon day'
      using errcode = '23514';
  end if;

  select bh.* into hours
  from public.business_hours as bh
  where bh.weekday = extract(dow from local_start)::smallint;

  if not found or not hours.is_open then
    raise exception 'salon is closed on the selected day'
      using errcode = '23514';
  end if;

  if local_start::time < hours.opens_at or local_end::time > hours.closes_at then
    raise exception 'booking is outside business hours'
      using errcode = '23514';
  end if;

  if hours.break_starts_at is not null
     and local_start::time < hours.break_ends_at
     and local_end::time > hours.break_starts_at then
    raise exception 'booking conflicts with the business break'
      using errcode = '23P01';
  end if;

  if exists (
    select 1 from public.schedule_blocks as sb
    where tstzrange(sb.starts_at, sb.ends_at, '[)')
          && tstzrange(new.starts_at, new.ends_at, '[)')
  ) then
    raise exception 'booking time conflicts with a schedule block'
      using errcode = '23P01';
  end if;

  return new;
end;
$$;

create or replace function agenda_salao_private.validate_schedule_block()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(731945210);

  if exists (
    select 1 from public.bookings as b
    where b.status in ('scheduled', 'confirmed')
      and tstzrange(b.starts_at, b.ends_at, '[)')
          && tstzrange(new.starts_at, new.ends_at, '[)')
  ) then
    raise exception 'schedule block conflicts with an active booking'
      using errcode = '23P01';
  end if;

  return new;
end;
$$;

revoke all on function
  agenda_salao_private.validate_booking_schedule(),
  agenda_salao_private.validate_schedule_block()
from public, anon, authenticated;

create trigger bookings_validate_schedule
before insert or update of starts_at, ends_at, status on public.bookings
for each row
when (new.status in ('scheduled', 'confirmed'))
execute function agenda_salao_private.validate_booking_schedule();

create trigger schedule_blocks_validate
before insert or update of starts_at, ends_at on public.schedule_blocks
for each row execute function agenda_salao_private.validate_schedule_block();

-- Shared appointment creation continues to reject inactive clients for a
-- standalone appointment. A booking completion may use its original client,
-- even when that client was deactivated after scheduling.
create or replace function agenda_salao_private.create_appointment_record(
  p_client_id bigint,
  p_performed_on date,
  p_service_ids bigint[],
  p_notes text,
  p_booking_id bigint,
  p_allowed_inactive_service_ids bigint[]
)
returns table (
  appointment_id bigint,
  appointment_client_id bigint,
  appointment_performed_on date,
  service_count integer,
  return_count integer
)
language plpgsql
volatile
security invoker
set search_path = ''
as $$
declare
  client_is_active boolean;
  booking_matches_client boolean := false;
  locked_service record;
  locked_service_count integer := 0;
  has_disallowed_inactive_service boolean := false;
  new_appointment_id bigint;
  inserted_service_count integer;
  generated_return_count integer;
begin
  if p_client_id is null then
    raise exception 'p_client_id is required' using errcode = '22023';
  end if;
  if p_performed_on is null then
    raise exception 'p_performed_on is required' using errcode = '22023';
  end if;
  if p_service_ids is null or cardinality(p_service_ids) = 0 then
    raise exception 'p_service_ids must contain at least one service' using errcode = '22023';
  end if;
  if array_position(p_service_ids, null) is not null then
    raise exception 'p_service_ids must not contain null values' using errcode = '22023';
  end if;
  if (select count(distinct requested_service_id)
      from unnest(p_service_ids) as requested(requested_service_id))
      <> cardinality(p_service_ids) then
    raise exception 'p_service_ids must not contain duplicate services' using errcode = '22023';
  end if;

  select c.active into client_is_active
  from public.clients as c where c.id = p_client_id for share;
  if not found then
    raise exception 'client % does not exist', p_client_id using errcode = '23503';
  end if;

  if p_booking_id is not null then
    select exists (
      select 1 from public.bookings as b
      where b.id = p_booking_id and b.client_id = p_client_id
    ) into booking_matches_client;
  end if;

  if not client_is_active and not booking_matches_client then
    raise exception 'client % is inactive', p_client_id using errcode = '55000';
  end if;

  for locked_service in
    select s.id, s.active from public.services as s
    where s.id = any (p_service_ids) order by s.id for share
  loop
    locked_service_count := locked_service_count + 1;
    has_disallowed_inactive_service := has_disallowed_inactive_service or (
      not locked_service.active and not (
        locked_service.id = any (coalesce(p_allowed_inactive_service_ids, array[]::bigint[]))
      )
    );
  end loop;

  if locked_service_count <> cardinality(p_service_ids) then
    raise exception 'one or more services do not exist' using errcode = '23503';
  end if;
  if has_disallowed_inactive_service then
    if p_booking_id is null then
      raise exception 'all services must be active' using errcode = '55000';
    end if;
    raise exception 'inactive services must have been planned in the booking' using errcode = '55000';
  end if;

  insert into public.appointments (client_id, performed_on, notes, booking_id)
  values (p_client_id, p_performed_on, p_notes, p_booking_id)
  returning id into new_appointment_id;

  insert into public.appointment_services (appointment_id, service_id)
  select new_appointment_id, requested.service_id
  from unnest(p_service_ids) with ordinality as requested(service_id, item_order)
  order by requested.item_order;
  get diagnostics inserted_service_count = row_count;

  select count(*)::integer into generated_return_count
  from public.returns as r
  join public.appointment_services as aps on aps.id = r.appointment_service_id
  where aps.appointment_id = new_appointment_id;

  return query select new_appointment_id, p_client_id, p_performed_on,
    inserted_service_count, generated_return_count;
end;
$$;

-- Enforce the completion clock inside the transaction before any appointment
-- row is created. Repeated calls for an already completed booking stay idempotent.
create or replace function agenda_salao_private.complete_booking(
  p_booking_id bigint,
  p_performed_on date,
  p_service_ids bigint[],
  p_notes text default null
)
returns table (
  booking_id bigint,
  appointment_id bigint,
  booking_status text,
  performed_on date,
  service_count integer
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  locked_booking public.bookings%rowtype;
  linked_appointment_id bigint;
  linked_performed_on date;
  linked_service_count integer;
  planned_service_ids bigint[];
  created_appointment record;
begin
  if not agenda_salao_private.is_salon_user() then
    raise exception 'only the authorized salon account can complete bookings' using errcode = '42501';
  end if;
  if p_booking_id is null then
    raise exception 'p_booking_id is required' using errcode = '22023';
  end if;

  select b.* into locked_booking
  from public.bookings as b where b.id = p_booking_id for update;
  if not found then
    raise exception 'booking % does not exist', p_booking_id using errcode = 'P0002';
  end if;

  select a.id, a.performed_on into linked_appointment_id, linked_performed_on
  from public.appointments as a where a.booking_id = p_booking_id;

  if locked_booking.status = 'completed' then
    if linked_appointment_id is null then
      raise exception 'completed booking % has no linked appointment', p_booking_id using errcode = 'XX000';
    end if;
    select count(*)::integer into linked_service_count
    from public.appointment_services as aps where aps.appointment_id = linked_appointment_id;
    return query select p_booking_id, linked_appointment_id, locked_booking.status,
      linked_performed_on, linked_service_count;
    return;
  end if;

  if locked_booking.status not in ('scheduled', 'confirmed') then
    raise exception 'booking % cannot be completed from status %', p_booking_id,
      locked_booking.status using errcode = '55000';
  end if;
  if locked_booking.starts_at > statement_timestamp() then
    raise exception 'booking cannot be completed before starts_at' using errcode = '55000';
  end if;
  if linked_appointment_id is not null then
    raise exception 'active booking % already has a linked appointment', p_booking_id using errcode = 'XX000';
  end if;

  select coalesce(array_agg(bs.service_id order by bs.service_id), array[]::bigint[])
  into planned_service_ids from public.booking_services as bs
  where bs.booking_id = p_booking_id;

  select * into created_appointment
  from agenda_salao_private.create_appointment_record(
    locked_booking.client_id, p_performed_on, p_service_ids, p_notes,
    p_booking_id, planned_service_ids
  );

  update public.bookings as b set status = 'completed' where b.id = p_booking_id;

  return query select p_booking_id, created_appointment.appointment_id,
    'completed'::text, created_appointment.appointment_performed_on,
    created_appointment.service_count;
end;
$$;

revoke all on function
  agenda_salao_private.create_appointment_record(bigint, date, bigint[], text, bigint, bigint[]),
  agenda_salao_private.complete_booking(bigint, date, bigint[], text)
from public, anon, authenticated;
grant execute on function
  agenda_salao_private.complete_booking(bigint, date, bigint[], text)
to authenticated;

comment on table public.business_hours is
  'One weekly operating-hours row per PostgreSQL weekday (Sunday = 0), interpreted in America/Sao_Paulo.';
comment on table public.schedule_blocks is
  'Exceptional closed periods stored as absolute timestamps and enforced against active bookings.';
